blog/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.post_list , name="post_list"),
    # <> 으로 동적으로 값을 받고, 해당하는 view 의 인수로 전달
    path('<int:post_id>/', views.post_detail, name="post_detail" ), 
    path('add/', views.post_add, name="post_add" ), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('posts/', include('blog.urls')),

]
# 정적 파일 처리를 웹 서버 대신 Django가 담당하는 것은 개발 단계의 편의성을 위해서만 사용해야 한다
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT,
)

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField("포스트 제목", max_length=100)
    content = models.TextField("포스트내용")
    thumbnail = models.ImageField("썸네일 이미지", upload_to="post", blank=True)

    def __str__(self) -> str:
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField("댓글내용")

    def __str__(self) -> str:
        return f"{self.post.title}의 댓글 (ID : {self.id})"

blog/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment

def index(request):
    return render(request,'index.html' )

def post_list(request):
    posts = Post.objects.order_by('-id') # 새로운 것이 위로 오게하기
    context = {
        "posts":posts
    }
    return render(request, "post_list.html", context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method == "POST":
        comment_content = request.POST['comment']
        Comment.objects.create(
            post=post,
            content=comment_content,
        )

    context = {
        "post":post,
    }
    return render(request, "post_detail.html", context)



def post_add(request):
    if request.method == "POST":
        print(request.FILES)
        title = request.POST["title"]
        content = request.POST["content"]
        thumbnail = request.FILES['thumbnail']
        post = Post.objects.create(
            title = title,
            content = content,
            thumbnail = thumbnail,
        )
        return redirect(f"/posts/{post.id}/") # posts/ 로 하면 뒤에 붙고, /posts/ 로 하면 8000/뒤에 붙는다
    
    else:
        print("method GET")
    return render(request, "post_add.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>

  <body>
    <div id="navbar">
      <span>pylog</span>
      <a href="{% url "post_add" %}" class="btn btn-primary">글 작성</a>
    </div>
    {% block content %}{% endblock content %}
    {% block script %}{% endblock script %}
  </body>

</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>

  <body>
    <div id="index">
      <h1>
        <a href="/posts/">pylog</a>
      </h1>
      <small>Life is short, You need Python.</small>
    </div>
  </body>

</html>

templates/post_add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>

  <body>
    <div id="navbar">
      <span>글 작성</span>
    </div>
    <div id="post-add">
      <!-- get 은 url로 데이터를 전송하는 방식. 하지만 여러 제약, 보안상 문제 많다 // 읽기, 조회용-->
      <!-- <form action="" method="get"> -->

      <!-- post 는 작성, 변경용 -->
      <!-- 이미지를 form으로 전달받으려면 enctype="multipart/form-data" -->
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
          <!-- label 과 input 은 for 과 id 로 연결 -->
          <!-- input 의 name과 textarea의 name으로 View 에 전달됨-->
          <label for="title">제목</label>
          <input type="text" name="title" id="title">
        </div>
        <div>
          <label for="content">내용</label>
          <textarea name="content"></textarea>
        </div>
        <div>
          <label for="">썸네일</label>
          <input type="file" name="thumbnail" id="">
        </div>
        <button type="submit" class="btn btn-primary">작성</button>
      </form>
    </div>
  </body>

</html>

templates/post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>

  <body>
    <div id="navbar">
      {% if post.thumbnail %}
        <img src="{{post.thumbnail.url}}" alt="">
      {% endif %}
      <span>{{post.title}}</span>
      <a href="{% url "post_list" %}" class="btn btn-primary">목록으로</a>
    </div>
    <div id="post-detail">
      <!-- |linebreaksbr filter 로 줄바꿈 적용 -->
      <p>{{post.content|linebreaksbr}}</p>
      <ul class="comments">
        {% for comment in post.comment_set.all %}
          <li class="comment">{{comment.content}}</li>

          {% empty %}
          <li class="commenn-empty">아직 댓글이 없습니다</li>
        {% endfor %}
      </ul>
      <form action="" method="post">
        {% csrf_token %}
        <textarea name="comment"></textarea>
        <button type="submit" class="btn btn-primary">댓글 작성</button>

      </form>
    </div>
  </body>

</html>

templates/post_list.html
{% extends "base.html" %}
{% comment %} {% load static %} {% endcomment %}
{% block content %}

    <div id="post-list">

      <ul class="posts">
        {% for post in posts %}
          <li class="post">
            <!-- url 태그는 urls.py 에서 정한 name을 써야 한다!!! -->
            <!-- 이름을 사용하여 템플릿에서 URL을 동적으로 생성하기 때문. -->
            <!-- urls.py 의 urlpatters 앞에 앱 이름을 지어놨다면? blog:post_detail -->
            <a href="{% url "post_detail" post.id %}">{{post.title}}</a>

            <p>{{post.content}}</p>
            <!-- 역방향 접근의 경우 함수의 ()을 빼야 한다 -->
            <ul class="comments">
              {% for comment in post.comment_set.all %}
                <li class="comment">{{comment.content}}</li>
                {% empty %}
                <li class="comment-empty">아직 댓글이 없습니다</li>
              {% endfor %}
            </ul>
            {% if post.thumbnail %}
              <img src="{{post.thumbnail.url}}" alt="">
            {% else %}
              <img src="" alt="">
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    </div>

    {% endblock content %}